# Generated by Django 4.2.1 on 2023-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveIntegerField(verbose_name='Book Rating'),
        ),
    ]
