# Generated by Django 4.2.1 on 2023-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Book Rating'),
        ),
    ]
