# Generated by Django 4.2.1 on 2023-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_remove_book_slug_alter_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Book Release Date'),
        ),
    ]
