# Generated by Django 4.2.1 on 2023-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
